### ISSUE TITLE
command-/ does not block comment/uncomment correctly

### ISSUE THREAD

**Issue by bshuler** [thejeffreystone/language-splunkconf#2]
command-/ does not block comment/uncomment correctly

If there is anything I can do to assist with this, let me know.

**Comment by thejeffreystone** [comment]
Yea. I haven't worked on that. If you have a solution send a pull request and I'll merge it. I'll try to schedule some time and get that fixed if not.

**Comment by thejeffreystone** [comment]
Thanks @shakeelmohamed!
